### ISSUE TITLE
Any plans to release 0.2.1 version?

### ISSUE THREAD

**Issue by priv-kweihmann** [mvdan/editorconfig#2]
https://pkg.go.dev/mvdan.cc/editorconfig lists 0.2.0 as the latest available, while https://github.com/mvdan/sh/blob/793d36450a0a5a466199b04c458fb4a1202cf641/go.mod#L15 references a 0.2.1 version.

**Comment by mvdan** [comment]
Sure, done: https://github.com/mvdan/editorconfig/releases/tag/v0.3.0

**Comment by mvdan** [comment]
To be clear, that 0.2.1 version you saw is a Go pseudo-version for a commit: https://go.dev/ref/mod#pseudo-versions
